import type { SimulationKey } from './excel-simulations';

export type Formula = {
  name: string;
  slug: string;
  category: 'Text' | 'Logical' | 'Lookup & Reference' | 'Math & Trig' | 'Date & Time' | 'Data Analysis' | 'Financial & Advanced';
  subcategory: string;
  syntax: string;
  description: string;
  steps: string[];
  simulationKey: SimulationKey;
};

export const formulas: Formula[] = [
  // Math & Trig / Statistics
  {
    name: 'SUM',
    slug: 'sum',
    category: 'Math & Trig',
    subcategory: 'Aggregation',
    syntax: 'SUM(number1, [number2], ...)',
    description: 'Adds all the numbers in a range of cells.',
    steps: [
      'Select a cell where you want the result.',
      'Type =SUM(',
      'Select the range of cells you want to add.',
      'Close the parenthesis and press Enter.',
    ],
    simulationKey: 'sum',
  },
  {
    name: 'AVERAGE',
    slug: 'average',
    category: 'Math & Trig',
    subcategory: 'Aggregation',
    syntax: 'AVERAGE(number1, [number2], ...)',
    description: 'Returns the average (arithmetic mean) of its arguments.',
    steps: [
      'Select a cell for the result.',
      'Type =AVERAGE(',
      'Select the range of numbers.',
      'Close the parenthesis and press Enter.',
    ],
    simulationKey: 'average',
  },
   {
    name: 'MAX',
    slug: 'max',
    category: 'Math & Trig',
    subcategory: 'Max & Min',
    syntax: 'MAX(number1, [number2], ...)',
    description: 'Returns the largest value in a set of values.',
    steps: ['Select a cell.', 'Type =MAX(', 'Select a range of numbers.', 'Press Enter.'],
    simulationKey: 'max',
  },
  {
    name: 'MIN',
    slug: 'min',
    category: 'Math & Trig',
    subcategory: 'Max & Min',
    syntax: 'MIN(number1, [number2], ...)',
    description: 'Returns the smallest number in a set of values.',
    steps: ['Select a cell.', 'Type =MIN(', 'Select a range of numbers.', 'Press Enter.'],
    simulationKey: 'min',
  },
  {
    name: 'COUNT',
    slug: 'count',
    category: 'Math & Trig',
    subcategory: 'Counting',
    syntax: 'COUNT(value1, [value2], ...)',
    description: 'Counts the number of cells that contain numbers.',
    steps: ['Select a cell.', 'Type =COUNT(', 'Select a range of cells.', 'Press Enter.'],
    simulationKey: 'count',
  },
  {
    name: 'COUNTA',
    slug: 'counta',
    category: 'Math & Trig',
    subcategory: 'Counting',
    syntax: 'COUNTA(value1, [value2], ...)',
    description: 'Counts the number of cells that are not empty in a range.',
    steps: ['Select a cell.', 'Type =COUNTA(', 'Select a range of cells.', 'Press Enter.'],
    simulationKey: 'counta',
  },
  {
    name: 'ROUND',
    slug: 'round',
    category: 'Math & Trig',
    subcategory: 'Rounding',
    syntax: 'ROUND(number, num_digits)',
    description: 'Rounds a number to a specified number of digits.',
    steps: ['Select a cell.', 'Type =ROUND(A1, 0) to round to the nearest integer.', 'Press Enter.'],
    simulationKey: 'round',
  },
  {
    name: 'ROUNDUP',
    slug: 'roundup',
    category: 'Math & Trig',
    subcategory: 'Rounding',
    syntax: 'ROUNDUP(number, num_digits)',
    description: 'Rounds a number up, away from zero.',
    steps: ['Select a cell.', 'Type =ROUNDUP(A1, 0) to round up to the nearest integer.', 'Press Enter.'],
    simulationKey: 'roundup',
  },
  {
    name: 'ROUNDDOWN',
    slug: 'rounddown',
    category: 'Math & Trig',
    subcategory: 'Rounding',
    syntax: 'ROUNDDOWN(number, num_digits)',
    description: 'Rounds a number down, toward zero.',
    steps: ['Select a cell.', 'Type =ROUNDDOWN(A1, 0) to round down to the nearest integer.', 'Press Enter.'],
    simulationKey: 'rounddown',
  },

  // Text
  {
    name: 'CONCAT',
    slug: 'concat',
    category: 'Text',
    subcategory: 'Joining',
    syntax: 'CONCAT(text1, [text2], ...)',
    description: 'Combines the text from multiple ranges and/or strings.',
    steps: ['Select a cell.', 'Type =CONCAT(A1, " ", B1) to join first and last names.', 'Press Enter.'],
    simulationKey: 'concat',
  },
  {
    name: 'TEXTJOIN',
    slug: 'textjoin',
    category: 'Text',
    subcategory: 'Joining',
    syntax: 'TEXTJOIN(delimiter, ignore_empty, text1, [text2], ...)',
    description: 'Combines the text from multiple ranges and/or strings with a specified delimiter.',
    steps: ['Select a cell.', 'Type =TEXTJOIN(", ", TRUE, A1:A3).', 'Press Enter.'],
    simulationKey: 'textjoin',
  },
  {
    name: 'TRIM',
    slug: 'trim',
    category: 'Text',
    subcategory: 'Cleaning',
    syntax: 'TRIM(text)',
    description: 'Removes all spaces from a text string except for single spaces between words.',
    steps: [
      'Select a cell for the cleaned text.',
      'Type =TRIM(',
      'Select the cell containing the text with extra spaces.',
      'Close the parenthesis and press Enter.',
    ],
    simulationKey: 'trim',
  },
  {
    name: 'UPPER',
    slug: 'upper',
    category: 'Text',
    subcategory: 'Case',
    syntax: 'UPPER(text)',
    description: 'Converts text to all uppercase letters.',
    steps: ['Select a cell.', 'Type =UPPER(A1).', 'Press Enter.'],
    simulationKey: 'upper',
  },
  {
    name: 'LOWER',
    slug: 'lower',
    category: 'Text',
    subcategory: 'Case',
    syntax: 'LOWER(text)',
    description: 'Converts all uppercase letters in a text string to lowercase.',
    steps: ['Select a cell.', 'Type =LOWER(A1).', 'Press Enter.'],
    simulationKey: 'lower',
  },
  {
    name: 'PROPER',
    slug: 'proper',
    category: 'Text',
    subcategory: 'Case',
    syntax: 'PROPER(text)',
    description: 'Capitalizes the first letter in each word of a text value.',
    steps: ['Select a cell.', 'Type =PROPER(A1).', 'Press Enter.'],
    simulationKey: 'proper',
  },
  {
    name: 'LEFT',
    slug: 'left',
    category: 'Text',
    subcategory: 'Extraction',
    syntax: 'LEFT(text, [num_chars])',
    description: 'Returns the specified number of characters from the start of a text string.',
    steps: ['To get first 3 characters: =LEFT(A1,3).', 'To extract text before a space: =LEFT(A1, FIND(" ", A1)-1).', 'Press Enter.'],
    simulationKey: 'left',
  },
  {
    name: 'RIGHT',
    slug: 'right',
    category: 'Text',
    subcategory: 'Extraction',
    syntax: 'RIGHT(text, [num_chars])',
    description: 'Returns the specified number of characters from the end of a text string.',
    steps: ['To extract text after a space: =RIGHT(A1, LEN(A1) - FIND(" ", A1)).', 'Press Enter.'],
    simulationKey: 'right',
  },
  
  // Lookup & Reference
  {
    name: 'VLOOKUP',
    slug: 'vlookup',
    category: 'Lookup & Reference',
    subcategory: 'Lookup',
    syntax: 'VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])',
    description: 'Looks for a value in the leftmost column of a table, and then returns a value in the same row from a column you specify.',
    steps: [
      'Identify the value you want to look up.',
      'Select the table array where the data resides.',
      'Specify the column index number to return a value from.',
      'Choose TRUE for an approximate match or FALSE for an exact match.',
    ],
    simulationKey: 'vlookup',
  },
  {
    name: 'HLOOKUP',
    slug: 'hlookup',
    category: 'Lookup & Reference',
    subcategory: 'Lookup',
    syntax: 'HLOOKUP(lookup_value, table_array, row_index_num, [range_lookup])',
    description: 'Looks for a value in the top row of a table, and then returns a value in the same column from a row you specify.',
    steps: ['Similar to VLOOKUP, but searches horizontally.', 'Formula: =HLOOKUP(A1,B1:C3,2,FALSE).', 'Press Enter.'],
    simulationKey: 'hlookup',
  },
  {
    name: 'INDEX-MATCH',
    slug: 'index-match',
    category: 'Lookup & Reference',
    subcategory: 'Lookup',
    syntax: 'INDEX(array, MATCH(lookup_value, lookup_array, [match_type]))',
    description: 'A powerful and flexible combination for performing lookups in any direction.',
    steps: ['INDEX returns a value from a range.', 'MATCH finds the position of a value.', 'Combine them: =INDEX(C1:C3, MATCH(A1,B1:B3,0)).'],
    simulationKey: 'index_match',
  },
  {
    name: 'XLOOKUP',
    slug: 'xlookup',
    category: 'Lookup & Reference',
    subcategory: 'Lookup',
    syntax: 'XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found], ...)',
    description: 'A modern and flexible replacement for VLOOKUP, HLOOKUP, and INDEX-MATCH.',
    steps: ['Specify lookup value, lookup array, and return array.', 'Formula: =XLOOKUP(A1,B1:B3,C1:C3,"Not Found").', 'Press Enter.'],
    simulationKey: 'xlookup',
  },
  {
    name: 'INDIRECT',
    slug: 'indirect',
    category: 'Lookup & Reference',
    subcategory: 'Reference',
    syntax: 'INDIRECT(ref_text, [a1])',
    description: 'Returns the reference specified by a text string.',
    steps: ['If cell A1 contains the text "B1", =INDIRECT(A1) will return the value of cell B1.', 'This is useful for creating dynamic references.'],
    simulationKey: 'indirect',
  },

  // Date & Time
  {
    name: 'TODAY',
    slug: 'today',
    category: 'Date & Time',
    subcategory: 'Current Date & Time',
    syntax: 'TODAY()',
    description: 'Returns the current date, which updates automatically.',
    steps: [
      'Select a cell.',
      'Type =TODAY()',
      'Press Enter to see today\'s date.',
    ],
    simulationKey: 'today',
  },
  {
    name: 'NOW',
    slug: 'now',
    category: 'Date & Time',
    subcategory: 'Current Date & Time',
    syntax: 'NOW()',
    description: 'Returns the current date and time.',
    steps: ['Select a cell.', 'Type =NOW().', 'Press Enter.'],
    simulationKey: 'now',
  },
  {
    name: 'DATEDIF',
    slug: 'datedif',
    category: 'Date & Time',
    subcategory: 'Date Difference',
    syntax: 'DATEDIF(start_date, end_date, unit)',
    description: 'Calculates the number of days, months, or years between two dates.',
    steps: ['To find days between dates in A1 and B1: =DATEDIF(A1,B1,"d").', 'Press Enter.'],
    simulationKey: 'datedif',
  },
  {
    name: 'YEAR',
    slug: 'year',
    category: 'Date & Time',
    subcategory: 'Extraction',
    syntax: 'YEAR(serial_number)',
    description: 'Returns the year of a date.',
    steps: ['Select a cell with a date in it (e.g., A1).', 'Type =YEAR(A1).', 'Press Enter.'],
    simulationKey: 'year',
  },
  {
    name: 'MONTH',
    slug: 'month',
    category: 'Date & Time',
    subcategory: 'Extraction',
    syntax: 'MONTH(serial_number)',
    description: 'Returns the month of a date.',
    steps: ['Select a cell with a date in it (e.g., A1).', 'Type =MONTH(A1).', 'Press Enter.'],
    simulationKey: 'month',
  },
  {
    name: 'TEXT (Weekday)',
    slug: 'text-weekday',
    category: 'Date & Time',
    subcategory: 'Formatting',
    syntax: 'TEXT(value, format_text)',
    description: 'Formats a number and converts it to text. Can be used to get the day of the week.',
    steps: ['To get the full weekday name from a date in A1: =TEXT(A1,"dddd").', 'Press Enter.'],
    simulationKey: 'text_weekday',
  },

  // Logical
  {
    name: 'IF',
    slug: 'if',
    category: 'Logical',
    subcategory: 'Conditional',
    syntax: 'IF(logical_test, [value_if_true], [value_if_false])',
    description: 'Checks whether a condition is met, and returns one value if TRUE, and another value if FALSE.',
    steps: [
      'Define the logical test (e.g., A1 > 50).',
      'Specify the value to return if the test is true ("Pass").',
      'Specify the value to return if the test is false ("Fail").',
      'Combine them: =IF(A1>50, "Pass", "Fail").',
    ],
    simulationKey: 'if',
  },
  {
    name: 'Nested IF',
    slug: 'nested-if',
    category: 'Logical',
    subcategory: 'Conditional',
    syntax: 'IF(logical_test1, value_if_true1, IF(logical_test2, ...))',
    description: 'Uses multiple IF functions to test for multiple conditions.',
    steps: ['Example for grading: =IF(A1>80,"A",IF(A1>60,"B","C")).', 'This checks conditions sequentially.'],
    simulationKey: 'nested_if',
  },
  {
    name: 'AND',
    slug: 'and',
    category: 'Logical',
    subcategory: 'Multiple Criteria',
    syntax: 'AND(logical1, [logical2], ...)',
    description: 'Returns TRUE if all of its arguments are TRUE.',
    steps: ['Often used with IF: =IF(AND(A1>50,B1>50),"Yes","No").', 'Checks if both conditions are met.'],
    simulationKey: 'and',
  },
  {
    name: 'OR',
    slug: 'or',
    category: 'Logical',
    subcategory: 'Multiple Criteria',
    syntax: 'OR(logical1, [logical2], ...)',
    description: 'Returns TRUE if any argument is TRUE.',
    steps: ['Often used with IF: =IF(OR(A1>50,B1>50),"Yes","No").', 'Checks if at least one condition is met.'],
    simulationKey: 'or',
  },

  // Data Analysis
  {
    name: 'RANK',
    slug: 'rank',
    category: 'Data Analysis',
    subcategory: 'Ranking',
    syntax: 'RANK(number, ref, [order])',
    description: 'Returns the rank of a number in a list of numbers.',
    steps: ['To rank value in A1 against the list A1:A5: =RANK(A1,A1:A5,0).', '0 for descending, 1 for ascending.'],
    simulationKey: 'rank',
  },
  {
    name: 'SUBTOTAL',
    slug: 'subtotal',
    category: 'Data Analysis',
    subcategory: 'Summarization',
    syntax: 'SUBTOTAL(function_num, ref1, ...)',
    description: 'Returns a subtotal in a list or database. It can ignore hidden rows from filtering.',
    steps: ['To SUM visible cells in A1:A10: =SUBTOTAL(9, A1:A10).', 'The number 9 specifies the SUM function.'],
    simulationKey: 'subtotal',
  },
  {
    name: 'UNIQUE',
    slug: 'unique',
    category: 'Data Analysis',
    subcategory: 'Filtering',
    syntax: 'UNIQUE(array, [by_col], [exactly_once])',
    description: 'Returns a list of unique values in a list or range.',
    steps: ['Select a cell.', 'Type =UNIQUE(A1:A10).', 'Press Enter to get a list of unique values.'],
    simulationKey: 'unique',
  },
  {
    name: 'FILTER',
    slug: 'filter',
    category: 'Data Analysis',
    subcategory: 'Filtering',
    syntax: 'FILTER(array, include, [if_empty])',
    description: 'Filters a range of data based on criteria you define.',
    steps: ['To filter values in A1:A10 that are > 50: =FILTER(A1:A10,A1:A10>50).', 'Press Enter.'],
    simulationKey: 'filter',
  },

  // Financial & Advanced
  {
    name: 'PMT',
    slug: 'pmt',
    category: 'Financial & Advanced',
    subcategory: 'Loan',
    syntax: 'PMT(rate, nper, pv, [fv], [type])',
    description: 'Calculates the payment for a loan based on constant payments and a constant interest rate.',
    steps: ['For a $100k loan over 2 years at 10% annual interest: =PMT(10%/12, 12*2, 100000).', 'Rate and nper must be in the same units (e.g., months).'],
    simulationKey: 'pmt',
  },
  {
    name: 'SLN',
    slug: 'sln',
    category: 'Financial & Advanced',
    subcategory: 'Depreciation',
    syntax: 'SLN(cost, salvage, life)',
    description: 'Returns the straight-line depreciation of an asset for one period.',
    steps: ['=SLN(cost, salvage_value, useful_life_in_years).', 'Example: =SLN(10000, 1000, 5).'],
    simulationKey: 'sln',
  },
  {
    name: 'NPV',
    slug: 'npv',
    category: 'Financial & Advanced',
    subcategory: 'Investment',
    syntax: 'NPV(rate, value1, [value2], ...)',
    description: 'Calculates the Net Present Value of an investment by using a discount rate and a series of future payments.',
    steps: ['Provide discount rate and range of cash flows.', 'Example: =NPV(10%, B1:B5).'],
    simulationKey: 'npv',
  },
  {
    name: 'IRR',
    slug: 'irr',
    category: 'Financial & Advanced',
    subcategory: 'Investment',
    syntax: 'IRR(values, [guess])',
    description: 'Returns the internal rate of return for a series of cash flows.',
    steps: ['Select the range of cash flows.', 'Example: =IRR(B1:B5).'],
    simulationKey: 'irr',
  },
];

export const categories = Array.from(new Set(formulas.map(f => f.category)));

export const getFormulasByCategory = (category: string) => {
  return formulas.filter(f => f.category === category);
};

export const getFormulaBySlug = (slug: string) => {
  return formulas.find(f => f.slug === slug);
};
