export interface ToolKeywordSet {
  primary: string;
  secondary: string[];
  headings: { intro: string; method: string; useCases: string; steps: string; faq: string };
}

const title = (slug: string) => slug.replace(/-calculator$| -calculator$/g, '').replace(/-/g, ' ');

const overrides: Record<string, ToolKeywordSet> = {
  'global-loan-optimizer': { primary: 'loan optimizer', secondary: ['loan comparison calculator', 'loan repayment optimizer', 'loan optimization calculator'], headings: { intro: 'Loan Optimizer', method: 'How a Loan Optimizer Works', useCases: 'Loan Optimization Use Cases', steps: 'How to Optimize a Loan', faq: 'Loan Optimizer FAQs' } },
  'crypto-tax-calculator': { primary: 'crypto tax calculator', secondary: ['cryptocurrency tax calculator', 'crypto capital gains calculator', 'bitcoin tax calculator'], headings: { intro: 'Crypto Tax Calculator', method: 'How a Crypto Tax Calculator Works', useCases: 'Crypto Tax Calculator Use Cases', steps: 'How to Calculate Crypto Taxes', faq: 'Crypto Tax Calculator FAQs' } },
  'forex-arbitrage-checker': { primary: 'forex arbitrage calculator', secondary: ['forex arbitrage checker', 'currency arbitrage calculator', 'forex arbitrage opportunities'], headings: { intro: 'Forex Arbitrage Checker', method: 'How a Forex Arbitrage Checker Works', useCases: 'Forex Arbitrage Use Cases', steps: 'How to Check Forex Arbitrage', faq: 'Forex Arbitrage Checker FAQs' } },
  'ai-invoice-generator': { primary: 'AI invoice generator', secondary: ['invoice generator', 'free invoice generator', 'online invoice maker'], headings: { intro: 'AI Invoice Generator', method: 'How an AI Invoice Generator Works', useCases: 'Invoice Generator Use Cases', steps: 'How to Create an Invoice Online', faq: 'AI Invoice Generator FAQs' } },
  'business-valuation-calculator': { primary: 'business valuation calculator', secondary: ['company valuation calculator', 'business value calculator', 'business worth calculator'], headings: { intro: 'Business Valuation Calculator', method: 'How a Business Valuation Calculator Works', useCases: 'Business Valuation Use Cases', steps: 'How to Estimate Business Value', faq: 'Business Valuation Calculator FAQs' } },
  'keyword-cluster-generator': { primary: 'keyword clustering tool', secondary: ['keyword cluster generator', 'SEO keyword clustering', 'keyword grouping tool'], headings: { intro: 'Keyword Cluster Generator', method: 'How a Keyword Clustering Tool Works', useCases: 'Keyword Clustering Use Cases', steps: 'How to Cluster SEO Keywords', faq: 'Keyword Cluster Generator FAQs' } },
  'content-gap-analyzer': { primary: 'content gap analysis tool', secondary: ['content gap analyzer', 'SEO content gap analysis', 'competitor content gap analysis'], headings: { intro: 'Content Gap Analyzer', method: 'How a Content Gap Analysis Tool Works', useCases: 'Content Gap Analysis Use Cases', steps: 'How to Find Content Gaps', faq: 'Content Gap Analyzer FAQs' } },
  '1-click-article-outline-generator': { primary: 'article outline generator', secondary: ['blog outline generator', 'AI article outline generator', 'content outline generator'], headings: { intro: 'Article Outline Generator', method: 'How an Article Outline Generator Works', useCases: 'Article Outline Use Cases', steps: 'How to Create an Article Outline', faq: 'Article Outline Generator FAQs' } },
  'ai-product-description-generator': { primary: 'AI product description generator', secondary: ['product description generator', 'ecommerce product description generator', 'AI product copywriter'], headings: { intro: 'AI Product Description Generator', method: 'How an AI Product Description Generator Works', useCases: 'Product Description Use Cases', steps: 'How to Write Product Descriptions with AI', faq: 'AI Product Description Generator FAQs' } },
  'api-latency-checker': { primary: 'API latency checker', secondary: ['API response time checker', 'API performance testing tool', 'API latency test'], headings: { intro: 'API Latency Checker', method: 'How an API Latency Checker Works', useCases: 'API Latency Testing Use Cases', steps: 'How to Check API Response Time', faq: 'API Latency Checker FAQs' } },
  'jwt-decoder-validator': { primary: 'JWT decoder and validator', secondary: ['JWT decoder', 'JWT validator', 'decode JWT online'], headings: { intro: 'JWT Decoder and Validator', method: 'How a JWT Decoder and Validator Works', useCases: 'JWT Debugging Use Cases', steps: 'How to Decode and Validate a JWT', faq: 'JWT Decoder FAQs' } },
  'regex-generator-from-text': { primary: 'regex generator', secondary: ['regex generator from text', 'regular expression generator', 'regex builder'], headings: { intro: 'Regex Generator from Text', method: 'How a Regex Generator Works', useCases: 'Regex Generator Use Cases', steps: 'How to Generate a Regular Expression', faq: 'Regex Generator FAQs' } },
  'json-excel-converter': { primary: 'JSON to Excel converter', secondary: ['convert JSON to Excel', 'JSON to XLSX converter', 'JSON Excel converter online'], headings: { intro: 'JSON to Excel Converter', method: 'How JSON to Excel Conversion Works', useCases: 'JSON to Excel Conversion Use Cases', steps: 'How to Convert JSON to Excel', faq: 'JSON to Excel Converter FAQs' } },
  'webhook-tester': { primary: 'webhook tester', secondary: ['webhook testing tool', 'test webhook online', 'webhook inspector'], headings: { intro: 'Webhook Tester', method: 'How a Webhook Tester Works', useCases: 'Webhook Testing Use Cases', steps: 'How to Test a Webhook', faq: 'Webhook Tester FAQs' } },
  'invoice-excel-extractor': { primary: 'invoice to Excel converter', secondary: ['extract invoice data to Excel', 'invoice data extractor', 'PDF invoice to Excel'], headings: { intro: 'Invoice to Excel Extractor', method: 'How Invoice Data Extraction Works', useCases: 'Invoice Data Extraction Use Cases', steps: 'How to Extract Invoice Data to Excel', faq: 'Invoice Excel Extractor FAQs' } },
  'free-image-file-compressor': { primary: 'free image compressor', secondary: ['compress image online', 'reduce image size', 'image optimizer', 'compress JPG and PNG'], headings: { intro: 'Free Image Compressor Online', method: 'How Image Compression Works', useCases: 'Image Compression Use Cases', steps: 'How to Compress an Image Online', faq: 'Image Compressor FAQs' } },
  'free-cheat-sheet-generator': { primary: 'free cheat sheet generator', secondary: ['AI cheat sheet generator', 'study cheat sheet maker', 'online cheat sheet generator'], headings: { intro: 'Free Cheat Sheet Generator', method: 'How an AI Cheat Sheet Generator Works', useCases: 'Cheat Sheet Generator Use Cases', steps: 'How to Make a Cheat Sheet Online', faq: 'Cheat Sheet Generator FAQs' } },
  'ai-humanizer': { primary: 'AI humanizer', secondary: ['AI text humanizer', 'humanize AI text', 'AI writing humanizer'], headings: { intro: 'AI Humanizer', method: 'How an AI Text Humanizer Works', useCases: 'AI Humanizer Use Cases', steps: 'How to Humanize AI Text', faq: 'AI Humanizer FAQs' } },
  'free-qr-code-generator': { primary: 'free QR code generator', secondary: ['QR code generator', 'QR code maker', 'create QR code online'], headings: { intro: 'Free QR Code Generator', method: 'How a QR Code Generator Works', useCases: 'QR Code Generator Use Cases', steps: 'How to Create a QR Code Online', faq: 'QR Code Generator FAQs' } },
  'plagiarism-checker': { primary: 'plagiarism checker', secondary: ['free plagiarism checker', 'online plagiarism checker', 'check plagiarism'], headings: { intro: 'Plagiarism Checker', method: 'How a Plagiarism Checker Works', useCases: 'Plagiarism Checker Use Cases', steps: 'How to Check Plagiarism Online', faq: 'Plagiarism Checker FAQs' } },
  'ai-tutor': { primary: 'AI tutor', secondary: ['AI study assistant', 'online AI tutor', 'AI homework help'], headings: { intro: 'AI Tutor', method: 'How an AI Tutor Works', useCases: 'AI Tutor Use Cases', steps: 'How to Use an AI Tutor', faq: 'AI Tutor FAQs' } },
  'excel-power-tools': { primary: 'Excel power tools', secondary: ['Excel tools online', 'Excel productivity tools', 'Excel data tools'], headings: { intro: 'Excel Power Tools Online', method: 'How Excel Power Tools Work', useCases: 'Excel Tool Use Cases', steps: 'How to Use Excel Power Tools', faq: 'Excel Power Tools FAQs' } },
  'image-compressor': { primary: 'image compressor', secondary: ['compress image online', 'reduce image size', 'compress JPG', 'compress PNG'], headings: { intro: 'Image Compressor Online', method: 'How an Image Compressor Works', useCases: 'Image Compression Use Cases', steps: 'How to Compress Images Online', faq: 'Image Compressor FAQs' } },
  'tinyurl-maker': { primary: 'URL shortener', secondary: ['short URL generator', 'link shortener', 'shorten a URL'], headings: { intro: 'URL Shortener and Short Link Generator', method: 'How a URL Shortener Works', useCases: 'URL Shortener Use Cases', steps: 'How to Shorten a URL', faq: 'URL Shortener FAQs' } },
  'pdf-to-word-converter': { primary: 'PDF to Word converter', secondary: ['convert PDF to Word', 'PDF to DOCX converter', 'PDF converter online'], headings: { intro: 'PDF to Word Converter Online', method: 'How PDF to Word Conversion Works', useCases: 'PDF to Word Conversion Use Cases', steps: 'How to Convert PDF to Word', faq: 'PDF to Word Converter FAQs' } },
  'emi-calculator': { primary: 'EMI calculator', secondary: ['loan EMI calculator', 'EMI payment calculator', 'monthly EMI calculator', 'home loan EMI calculator'], headings: { intro: 'EMI Calculator', method: 'How an EMI Calculator Works', useCases: 'EMI Calculator Use Cases', steps: 'How to Calculate EMI Online', faq: 'EMI Calculator FAQs' } },
  'loan-calculator': { primary: 'loan calculator', secondary: ['loan payment calculator', 'loan interest calculator', 'monthly loan payment calculator'], headings: { intro: 'Loan Calculator', method: 'How a Loan Calculator Works', useCases: 'Loan Calculator Use Cases', steps: 'How to Calculate Loan Payments', faq: 'Loan Calculator FAQs' } },
  'mortgage-calculator': { primary: 'mortgage calculator', secondary: ['mortgage payment calculator', 'home loan calculator', 'mortgage payment estimator'], headings: { intro: 'Mortgage Calculator', method: 'How a Mortgage Calculator Works', useCases: 'Mortgage Calculator Use Cases', steps: 'How to Calculate a Mortgage Payment', faq: 'Mortgage Calculator FAQs' } },
  'home-loan-calculator': { primary: 'home loan calculator', secondary: ['home loan EMI calculator', 'home loan payment calculator', 'home loan interest calculator'], headings: { intro: 'Home Loan Calculator', method: 'How a Home Loan Calculator Works', useCases: 'Home Loan Calculator Use Cases', steps: 'How to Calculate Home Loan EMI', faq: 'Home Loan Calculator FAQs' } },
  'car-loan-calculator': { primary: 'car loan calculator', secondary: ['auto loan calculator', 'car payment calculator', 'car loan payment calculator'], headings: { intro: 'Car Loan Calculator', method: 'How a Car Loan Calculator Works', useCases: 'Car Loan Calculator Use Cases', steps: 'How to Calculate a Car Loan Payment', faq: 'Car Loan Calculator FAQs' } },
  'personal-loan-calculator': { primary: 'personal loan calculator', secondary: ['personal loan payment calculator', 'personal loan interest calculator', 'loan calculator with interest'], headings: { intro: 'Personal Loan Calculator', method: 'How a Personal Loan Calculator Works', useCases: 'Personal Loan Calculator Use Cases', steps: 'How to Calculate Personal Loan Payments', faq: 'Personal Loan Calculator FAQs' } },
  'student-loan-calculator': { primary: 'student loan calculator', secondary: ['student loan payment calculator', 'student loan interest calculator', 'student loan repayment calculator'], headings: { intro: 'Student Loan Calculator', method: 'How a Student Loan Calculator Works', useCases: 'Student Loan Calculator Use Cases', steps: 'How to Calculate Student Loan Payments', faq: 'Student Loan Calculator FAQs' } },
  'credit-card-payoff-calculator': { primary: 'credit card payoff calculator', secondary: ['credit card payment calculator', 'credit card debt payoff calculator', 'credit card interest calculator'], headings: { intro: 'Credit Card Payoff Calculator', method: 'How a Credit Card Payoff Calculator Works', useCases: 'Credit Card Payoff Calculator Use Cases', steps: 'How to Calculate Credit Card Payoff Time', faq: 'Credit Card Payoff Calculator FAQs' } },
  'interest-calculator': { primary: 'interest calculator', secondary: ['interest rate calculator', 'loan interest calculator', 'calculate interest'], headings: { intro: 'Interest Calculator', method: 'How an Interest Calculator Works', useCases: 'Interest Calculator Use Cases', steps: 'How to Calculate Interest Online', faq: 'Interest Calculator FAQs' } },
  'simple-interest-calculator': { primary: 'simple interest calculator', secondary: ['simple interest formula calculator', 'calculate simple interest', 'simple interest online calculator'], headings: { intro: 'Simple Interest Calculator', method: 'How a Simple Interest Calculator Works', useCases: 'Simple Interest Calculator Use Cases', steps: 'How to Calculate Simple Interest', faq: 'Simple Interest Calculator FAQs' } },
  'compound-interest-calculator': { primary: 'compound interest calculator', secondary: ['compound interest formula', 'daily compound interest calculator', 'monthly compound interest calculator', 'investment growth calculator'], headings: { intro: 'Compound Interest Calculator', method: 'How Compound Interest Works', useCases: 'Compound Interest Calculator Use Cases', steps: 'How to Calculate Compound Interest', faq: 'Compound Interest Calculator FAQs' } },
  'investment-return-calculator': { primary: 'investment return calculator', secondary: ['investment growth calculator', 'rate of return calculator', 'investment returns calculator'], headings: { intro: 'Investment Return Calculator', method: 'How an Investment Return Calculator Works', useCases: 'Investment Return Calculator Use Cases', steps: 'How to Calculate Investment Returns', faq: 'Investment Return Calculator FAQs' } },
  'roi-calculator': { primary: 'ROI calculator', secondary: ['return on investment calculator', 'investment ROI calculator', 'calculate ROI'], headings: { intro: 'ROI Calculator', method: 'How a Return on Investment Calculator Works', useCases: 'ROI Calculator Use Cases', steps: 'How to Calculate ROI', faq: 'ROI Calculator FAQs' } },
  'inflation-calculator': { primary: 'inflation calculator', secondary: ['inflation rate calculator', 'purchasing power calculator', 'future value inflation calculator'], headings: { intro: 'Inflation Calculator', method: 'How an Inflation Calculator Works', useCases: 'Inflation Calculator Use Cases', steps: 'How to Calculate Inflation Impact', faq: 'Inflation Calculator FAQs' } },
  'stopwatch': { primary: 'online stopwatch', secondary: ['free stopwatch', 'online timer', 'lap timer'], headings: { intro: 'Online Stopwatch', method: 'How an Online Stopwatch Works', useCases: 'Stopwatch and Timer Use Cases', steps: 'How to Use the Online Stopwatch', faq: 'Online Stopwatch FAQs' } },
  'scientific-calculator': { primary: 'scientific calculator', secondary: ['online scientific calculator', 'advanced calculator', 'math calculator'], headings: { intro: 'Scientific Calculator Online', method: 'How a Scientific Calculator Works', useCases: 'Scientific Calculator Use Cases', steps: 'How to Use a Scientific Calculator', faq: 'Scientific Calculator FAQs' } },
  'take-home-pay-calculator': { primary: 'take home pay calculator', secondary: ['salary after tax calculator', 'net pay calculator', 'paycheck calculator'], headings: { intro: 'Take Home Pay Calculator', method: 'How a Take Home Pay Calculator Works', useCases: 'Take Home Pay Calculator Use Cases', steps: 'How to Calculate Take Home Pay', faq: 'Take Home Pay Calculator FAQs' } },
  '401k-calculator': { primary: '401k calculator', secondary: ['401k retirement calculator', '401k contribution calculator', 'retirement savings calculator'], headings: { intro: '401k Calculator', method: 'How a 401k Calculator Works', useCases: '401k Calculator Use Cases', steps: 'How to Calculate 401k Growth', faq: '401k Calculator FAQs' } },
  'pension-calculator': { primary: 'pension calculator', secondary: ['pension retirement calculator', 'retirement income calculator', 'pension payout calculator'], headings: { intro: 'Pension Calculator', method: 'How a Pension Calculator Works', useCases: 'Pension Calculator Use Cases', steps: 'How to Estimate Pension Income', faq: 'Pension Calculator FAQs' } },
  'auto-loan-calculator': { primary: 'auto loan calculator', secondary: ['car loan calculator', 'auto payment calculator', 'car payment calculator'], headings: { intro: 'Auto Loan Calculator', method: 'How an Auto Loan Calculator Works', useCases: 'Auto Loan Calculator Use Cases', steps: 'How to Calculate an Auto Loan Payment', faq: 'Auto Loan Calculator FAQs' } },
  'age-calculator': { primary: 'age calculator', secondary: ['calculate age', 'age in years months days', 'date of birth age calculator'], headings: { intro: 'Age Calculator', method: 'How an Age Calculator Works', useCases: 'Age Calculator Use Cases', steps: 'How to Calculate Age from Date of Birth', faq: 'Age Calculator FAQs' } },
  'retirement-calculator': { primary: 'retirement calculator', secondary: ['retirement savings calculator', 'retirement income calculator', 'retirement planning calculator'], headings: { intro: 'Retirement Calculator', method: 'How a Retirement Calculator Works', useCases: 'Retirement Calculator Use Cases', steps: 'How to Estimate Retirement Savings', faq: 'Retirement Calculator FAQs' } },
  'income-tax-calculator': { primary: 'income tax calculator', secondary: ['income tax calculator India', 'tax calculator', 'salary tax calculator'], headings: { intro: 'Income Tax Calculator', method: 'How an Income Tax Calculator Works', useCases: 'Income Tax Calculator Use Cases', steps: 'How to Estimate Income Tax', faq: 'Income Tax Calculator FAQs' } },
  'mortgage-payment-calculator': { primary: 'mortgage payment calculator', secondary: ['mortgage calculator', 'monthly mortgage payment calculator', 'home loan payment calculator'], headings: { intro: 'Mortgage Payment Calculator', method: 'How a Mortgage Payment Calculator Works', useCases: 'Mortgage Payment Calculator Use Cases', steps: 'How to Calculate a Monthly Mortgage Payment', faq: 'Mortgage Payment Calculator FAQs' } },
  'nps-calculator': { primary: 'NPS calculator', secondary: ['National Pension System calculator', 'NPS pension calculator', 'NPS retirement calculator'], headings: { intro: 'NPS Calculator', method: 'How an NPS Calculator Works', useCases: 'NPS Calculator Use Cases', steps: 'How to Estimate NPS Retirement Value', faq: 'NPS Calculator FAQs' } },
  'sales-tax-calculator': { primary: 'sales tax calculator', secondary: ['sales tax rate calculator', 'calculate sales tax', 'price after tax calculator'], headings: { intro: 'Sales Tax Calculator', method: 'How a Sales Tax Calculator Works', useCases: 'Sales Tax Calculator Use Cases', steps: 'How to Calculate Sales Tax', faq: 'Sales Tax Calculator FAQs' } },
  'random-number-generator': { primary: 'random number generator', secondary: ['random number picker', 'random integer generator', 'generate random numbers'], headings: { intro: 'Random Number Generator', method: 'How a Random Number Generator Works', useCases: 'Random Number Generator Use Cases', steps: 'How to Generate Random Numbers', faq: 'Random Number Generator FAQs' } },
  'social-security-calculator': { primary: 'Social Security calculator', secondary: ['Social Security benefits calculator', 'retirement benefits calculator', 'Social Security retirement calculator'], headings: { intro: 'Social Security Calculator', method: 'How a Social Security Calculator Works', useCases: 'Social Security Calculator Use Cases', steps: 'How to Estimate Social Security Benefits', faq: 'Social Security Calculator FAQs' } },
  'salary-calculator': { primary: 'salary calculator', secondary: ['salary after tax calculator', 'annual salary calculator', 'hourly to salary calculator'], headings: { intro: 'Salary Calculator', method: 'How a Salary Calculator Works', useCases: 'Salary Calculator Use Cases', steps: 'How to Calculate Salary and Pay', faq: 'Salary Calculator FAQs' } },
  'calorie-calculator': { primary: 'calorie calculator', secondary: ['daily calorie calculator', 'calorie intake calculator', 'calories per day calculator'], headings: { intro: 'Calorie Calculator', method: 'How a Calorie Calculator Works', useCases: 'Calorie Calculator Use Cases', steps: 'How to Estimate Daily Calorie Needs', faq: 'Calorie Calculator FAQs' } },
  'gst-calculator': { primary: 'GST calculator', secondary: ['GST tax calculator', 'GST calculator India', 'calculate GST'], headings: { intro: 'GST Calculator', method: 'How a GST Calculator Works', useCases: 'GST Calculator Use Cases', steps: 'How to Calculate GST', faq: 'GST Calculator FAQs' } },
  'profit-margin-calculator': { primary: 'profit margin calculator', secondary: ['profit percentage calculator', 'gross profit margin calculator', 'calculate profit margin'], headings: { intro: 'Profit Margin Calculator', method: 'How a Profit Margin Calculator Works', useCases: 'Profit Margin Calculator Use Cases', steps: 'How to Calculate Profit Margin', faq: 'Profit Margin Calculator FAQs' } },
  'percentage-calculator': { primary: 'percentage calculator', secondary: ['percentage change calculator', 'percent calculator', 'calculate percentage'], headings: { intro: 'Percentage Calculator', method: 'How a Percentage Calculator Works', useCases: 'Percentage Calculator Use Cases', steps: 'How to Calculate Percentages', faq: 'Percentage Calculator FAQs' } },
  'time-zone-converter': { primary: 'time zone converter', secondary: ['timezone converter', 'world time converter', 'time difference calculator'], headings: { intro: 'Time Zone Converter', method: 'How a Time Zone Converter Works', useCases: 'Time Zone Converter Use Cases', steps: 'How to Convert Time Zones', faq: 'Time Zone Converter FAQs' } },
  'ppf-calculator': { primary: 'PPF calculator', secondary: ['PPF interest calculator', 'PPF maturity calculator', 'PPF investment calculator'], headings: { intro: 'PPF Calculator', method: 'How a PPF Calculator Works', useCases: 'PPF Calculator Use Cases', steps: 'How to Calculate PPF Maturity', faq: 'PPF Calculator FAQs' } },
  'bmi-calculator': { primary: 'BMI calculator', secondary: ['BMI calculator for adults', 'BMI by height and weight', 'body mass index calculator'], headings: { intro: 'BMI Calculator', method: 'How a BMI Calculator Works', useCases: 'BMI Calculator Use Cases', steps: 'How to Calculate BMI', faq: 'BMI Calculator FAQs' } },
  'date-calculator': { primary: 'date calculator', secondary: ['date difference calculator', 'days between dates calculator', 'add days to date'], headings: { intro: 'Date Calculator', method: 'How a Date Calculator Works', useCases: 'Date Calculator Use Cases', steps: 'How to Calculate the Difference Between Dates', faq: 'Date Calculator FAQs' } },
  'currency-converter': { primary: 'currency converter', secondary: ['currency exchange calculator', 'exchange rate converter', 'convert currency online'], headings: { intro: 'Currency Converter', method: 'How a Currency Converter Works', useCases: 'Currency Converter Use Cases', steps: 'How to Convert Currency Online', faq: 'Currency Converter FAQs' } },
  'sip-calculator': { primary: 'SIP calculator', secondary: ['SIP investment calculator', 'SIP return calculator', 'mutual fund SIP calculator'], headings: { intro: 'SIP Calculator', method: 'How a SIP Calculator Works', useCases: 'SIP Calculator Use Cases', steps: 'How to Calculate SIP Returns', faq: 'SIP Calculator FAQs' } },
  'fd-calculator': { primary: 'FD calculator', secondary: ['fixed deposit calculator', 'FD maturity calculator', 'fixed deposit interest calculator'], headings: { intro: 'FD Calculator', method: 'How an FD Calculator Works', useCases: 'FD Calculator Use Cases', steps: 'How to Calculate Fixed Deposit Maturity', faq: 'FD Calculator FAQs' } },
  'break-even-calculator': { primary: 'break even calculator', secondary: ['break even point calculator', 'break even analysis calculator', 'calculate break even point'], headings: { intro: 'Break Even Calculator', method: 'How a Break Even Calculator Works', useCases: 'Break Even Calculator Use Cases', steps: 'How to Calculate the Break Even Point', faq: 'Break Even Calculator FAQs' } },
  'tip-calculator': { primary: 'tip calculator', secondary: ['restaurant tip calculator', 'tip percentage calculator', 'bill splitter and tip calculator'], headings: { intro: 'Tip Calculator', method: 'How a Tip Calculator Works', useCases: 'Tip Calculator Use Cases', steps: 'How to Calculate a Tip', faq: 'Tip Calculator FAQs' } },
  'discount-calculator': { primary: 'discount calculator', secondary: ['percentage discount calculator', 'sale price calculator', 'discount percentage calculator'], headings: { intro: 'Discount Calculator', method: 'How a Discount Calculator Works', useCases: 'Discount Calculator Use Cases', steps: 'How to Calculate a Discount', faq: 'Discount Calculator FAQs' } },
};

const generic = (slug: string): ToolKeywordSet => {
  const p = title(slug);
  const cap = p.replace(/\b\w/g, c => c.toUpperCase());
  return { primary: p, secondary: [`free ${p}`, `${p} online`, `online ${p}`], headings: { intro: cap, method: `How ${p} Works`, useCases: `${cap} Use Cases`, steps: `How to Use ${p} Online`, faq: `${cap} FAQs` } };
};

export function getToolKeywords(slug: string): ToolKeywordSet {
  return overrides[slug] ?? generic(slug);
}
