from pathlib import Path
p=Path('/mnt/data/work/src/lib/tools.ts')
s=p.read_text()
insert=r'''
  // ==========================================
  // EXPANSION: CALCULATORS & EVERYDAY UTILITIES
  // ==========================================
'''
data=[
('Stopwatch','stopwatch','Business','Clock3','A precise online stopwatch with start, pause, and reset controls and hundredth-second timing.','Use a browser-based stopwatch for workouts, study sessions, presentations, experiments, cooking, sports drills, and everyday timing.','online stopwatch, stopwatch timer, free stopwatch, digital stopwatch'),
('Retirement Calculator','retirement-calculator','Finance','Landmark','Estimate retirement savings growth, future portfolio value, contributions, and the effect of time and expected returns.','Plan retirement scenarios by comparing current savings, annual contributions, retirement age, and an assumed investment return.','retirement calculator, retirement savings calculator, retirement planning calculator, 401k retirement calculator'),
('Pension Calculator','pension-calculator','Finance','BadgeDollarSign','Estimate an illustrative pension from salary, years of service, and a pension accrual rate.','Model a pension scenario with transparent assumptions so you can understand how service and salary can affect an estimated benefit.','pension calculator, pension estimate calculator, retirement pension calculator'),
('SIP Calculator','sip-calculator','Finance','TrendingUp','Estimate SIP investment growth, total contributions, and potential returns from recurring investments.','Calculate the projected value of monthly SIP contributions using an assumed annual return and investment period.','SIP calculator, mutual fund SIP calculator, monthly SIP calculator, SIP return calculator'),
('FD Calculator','fd-calculator','Finance','PiggyBank','Estimate fixed deposit maturity value and interest using deposit amount, rate, tenure, and compounding frequency.','Compare fixed-deposit scenarios by changing principal, interest rate, tenure, and compounding frequency.','FD calculator, fixed deposit calculator, FD maturity calculator, fixed deposit interest calculator'),
('PPF Calculator','ppf-calculator','Finance','Landmark','Estimate PPF growth from annual contributions, an assumed interest rate, and the investment period.','Use an assumption-based PPF projection to understand contributions, estimated interest, and future value over time.','PPF calculator, PPF maturity calculator, PPF interest calculator'),
('NPS Calculator','nps-calculator','Finance','Landmark','Estimate NPS corpus growth, annuity allocation, and the remaining lump-sum portion from recurring contributions.','Explore retirement corpus scenarios by adjusting contributions, expected return, years to retirement, and annuity allocation.','NPS calculator, NPS pension calculator, NPS corpus calculator'),
('401(k) Calculator','401k-calculator','Finance','BadgeDollarSign','Estimate 401(k) growth from your current balance, employee contributions, employer match, return assumption, and years.','Model a simplified 401(k) projection for US retirement planning and compare the impact of contributions and employer matching.','401k calculator, 401(k) calculator, 401k retirement calculator, employer match calculator'),
('Social Security Calculator','social-security-calculator','Finance','Landmark','Estimate future Social Security benefit growth from a current monthly benefit and an assumed annual adjustment.','Create an illustrative benefit projection while keeping the adjustment assumption visible rather than presenting it as an official SSA quote.','Social Security calculator, Social Security benefit calculator, retirement benefit calculator'),
('Income Tax Calculator','income-tax-calculator','Finance','Receipt','Estimate income tax and after-tax income using annual income and an effective tax rate.','Use a simple effective-rate model for planning and compare scenarios without pretending to reproduce every federal, state, or national tax rule.','income tax calculator, tax calculator, income tax estimator, tax estimate calculator'),
('Take-Home Pay Calculator','take-home-pay-calculator','Finance','WalletCards','Estimate annual and monthly take-home pay after income tax, payroll taxes, retirement contributions, and other deductions.','Model an approximate paycheck outcome from gross pay and transparent deduction assumptions.','take home pay calculator, paycheck calculator, net pay calculator, salary after tax calculator'),
('Salary Calculator','salary-calculator','Finance','WalletCards','Convert a pay amount into annual, monthly, and hourly equivalents using work hours and paid weeks.','Compare compensation formats and translate an hourly or weekly rate into an annual salary estimate.','salary calculator, hourly to salary calculator, annual salary calculator, pay calculator'),
('GST Calculator','gst-calculator','Finance','Receipt','Calculate GST amount and the total price from a pre-tax amount and GST rate.','Use the GST calculator for Indian pricing, invoices, retail quotes, and quick tax-inclusive calculations.','GST calculator, GST calculation, GST inclusive calculator, GST tax calculator India'),
('Sales Tax Calculator','sales-tax-calculator','Finance','Receipt','Calculate sales tax and total purchase cost from a pre-tax price and sales-tax rate.','Estimate tax-inclusive purchase prices for US sales-tax scenarios using the rate you enter.','sales tax calculator, sales tax calculation, tax inclusive price calculator, US sales tax calculator'),
('Percentage Calculator','percentage-calculator','Business','Percent','Solve common percentage calculations quickly, including a percentage of a number and percentage-to-decimal conversion.','Use percentage calculations for discounts, grades, business metrics, finance, statistics, and everyday comparisons.','percentage calculator, percentage of a number, percent calculator, percentage change calculator'),
('Age Calculator','age-calculator','Business','CalendarDays','Calculate age from a birth date to a target date and show the elapsed time in years and days.','Find an exact date-based age for forms, planning, milestones, birthdays, eligibility checks, and personal records.','age calculator, calculate age, exact age calculator, age in years months days'),
('Date Calculator','date-calculator','Business','CalendarDays','Calculate days between dates and add or subtract a chosen number of days from a start date.','Use date arithmetic for deadlines, project planning, contracts, schedules, travel, and date-based calculations.','date calculator, days between dates, date difference calculator, add days to date'),
('BMI Calculator','bmi-calculator','Health','HeartPulse','Calculate body mass index from height and weight using a standard BMI formula.','Get a quick BMI estimate for general awareness. BMI is a screening measure and should not be treated as a diagnosis or complete health assessment.','BMI calculator, body mass index calculator, BMI calculator kg cm'),
('Calorie Calculator','calorie-calculator','Health','Flame','Estimate basal metabolic rate and daily calorie needs from age, sex, height, weight, and activity level.','Use calorie estimates as a starting point for general planning; individual energy needs vary with health, body composition, activity, and other factors.','calorie calculator, daily calorie calculator, TDEE calculator, BMR calorie calculator'),
('Mortgage Payment Calculator','mortgage-payment-calculator','Finance','House','Calculate estimated monthly principal-and-interest mortgage payments, total payments, and total interest.','Compare mortgage payment scenarios by changing the loan amount, interest rate, and repayment term.','mortgage payment calculator, monthly mortgage calculator, mortgage calculator USA'),
('Auto Loan Calculator','auto-loan-calculator','Finance','Car','Estimate vehicle loan payments, amount financed, and total interest from vehicle price, down payment, rate, and term.','Compare auto financing scenarios before shopping for a vehicle or evaluating a lender offer.','auto loan calculator, car payment calculator, vehicle loan calculator'),
('Discount Calculator','discount-calculator','Business','Tag','Calculate discount amount, sale price, and savings from an original price and discount percentage.','Quickly work out sale prices for shopping, promotions, invoices, retail pricing, and business offers.','discount calculator, sale price calculator, percentage discount calculator'),
('Tip Calculator','tip-calculator','Business','Utensils','Calculate tip, total bill, and per-person cost for restaurants, services, and shared bills.','Choose a tip percentage and number of people to split a bill without manual arithmetic.','tip calculator, restaurant tip calculator, tip split calculator, gratuity calculator'),
('Profit Margin Calculator','profit-margin-calculator','Business','BriefcaseBusiness','Calculate profit, profit margin, and markup from cost and selling price.','Use profit margin and markup calculations to evaluate pricing, products, services, and business scenarios.','profit margin calculator, profit calculator, markup calculator, gross margin calculator'),
('Break-Even Calculator','break-even-calculator','Business','Scale','Calculate the units and revenue required to cover fixed and variable costs at a given selling price.','Understand the sales volume needed to reach break-even and test how pricing or costs change the threshold.','break even calculator, break even point calculator, break even analysis'),
('Currency Converter','currency-converter','Business','Globe2','Convert between major currencies using a transparent exchange-rate calculation and reference-rate lookup when available.','Use the converter for travel, budgeting, international pricing, invoices, and quick currency comparisons.','currency converter, USD to INR converter, INR to USD converter, exchange rate calculator'),
('Time Zone Converter','time-zone-converter','Business','Globe2','Convert a local date and time between major time zones around the world, including US, Europe, and Asia.','Coordinate meetings, travel, remote teams, launches, interviews, and events across time zones.','time zone converter, timezone converter, US time zone converter, IST to EST converter'),
('Scientific Calculator','scientific-calculator','Business','Calculator','Perform arithmetic, trigonometric, logarithmic, root, and power calculations in a responsive browser calculator.','Use scientific functions for school, engineering, technical work, mathematics, and everyday calculations.','scientific calculator, online scientific calculator, math calculator'),
('Random Number Generator','random-number-generator','Business','Shuffle','Generate random integers between a custom minimum and maximum, with support for multiple results.','Generate numbers for games, sampling, testing, classroom activities, raffles, and other non-security use cases.','random number generator, random integer generator, random number picker'),
]
# insert before final ];
pos=s.rfind('\n];')
block=insert
for name,slug,cat,icon,desc,longd,keywords in data:
    kw=[x.strip() for x in keywords.split(',')]
    block += f'''  {{\n    name: {name!r},\n    slug: {slug!r},\n    category: {cat!r},\n    icon: {icon!r},\n    description: {desc!r},\n    longDescription: {longd!r},\n    features: ['Responsive design for desktop and mobile', 'Clear inputs with immediate calculations', 'Transparent assumptions and result breakdowns', 'Useful for everyday planning and comparison', 'No account required for basic calculations'],\n    howItWorks: ['Enter the requested values and assumptions', 'Review the inputs and adjust them for your scenario', 'Calculate the result instantly in your browser', 'Compare the output with other realistic scenarios'],\n    useCases: ['Everyday personal planning', 'Students and professionals checking calculations', 'Businesses comparing practical scenarios', 'Users preparing estimates before making decisions'],\n    keywords: {kw!r},\n    metaTitle: {name!r} + ' - Free Online Calculator | All2ools',\n    metaDescription: {desc!r} + ' Free, responsive online calculator from All2ools.',\n  }},\n'''
s=s[:pos]+"\n"+block+s[pos:]
p.write_text(s)
print('added',len(data))
